### ISSUE TITLE
Crash due to OOM leads to open network connection.

### ISSUE THREAD

**Issue by justinabrahms** [ssbc/go-ssb#95] opened 2021-04-25 21:38 UTC
I was doing an `sbotcli connect hostname.here` and ran out of memory. It also broke the socket.

1gb of ram (700mb available) w/ 2gb of free swap. 

I'd love it if this would work in low memory footprints, but correctly closing the socket seems more important.

```

runtime stack:
runtime.throw(0xb0920e, 0x16)
        /snap/go/7360/src/runtime/panic.go:1117 +0x72 fp=0x7ffd37620040 sp=0x7ffd37620010 pc=0x439452
runtime.sysMap(0xc000000000, 0x4000000, 0x11285d0)
        /snap/go/7360/src/runtime/mem_linux.go:169 +0xc6 fp=0x7ffd37620080 sp=0x7ffd37620040 pc=0x41bfe6
runtime.(*mheap).sysAlloc(0x110eaa0, 0x400000, 0x0, 0x0)
        /snap/go/7360/src/runtime/malloc.go:729 +0x1e5 fp=0x7ffd37620128 sp=0x7ffd37620080 pc=0x40f485
runtime.(*mheap).grow(0x110eaa0, 0x1, 0x0)
        /snap/go/7360/src/runtime/mheap.go:1346 +0x85 fp=0x7ffd37620190 sp=0x7ffd37620128 pc=0x42b185
runtime.(*mheap).allocSpan(0x110eaa0, 0x1, 0x2c00, 0x0)
        /snap/go/7360/src/runtime/mheap.go:1173 +0x609 fp=0x7ffd37620210 sp=0x7ffd37620190 pc=0x42af89
runtime.(*mheap).alloc.func1()
        /snap/go/7360/src/runtime/mheap.go:910 +0x59 fp=0x7ffd37620260 sp=0x7ffd37620210 pc=0x4662d9
runtime.(*mheap).alloc(0x110eaa0, 0x1, 0x220000012c, 0xffffffff)
        /snap/go/7360/src/runtime/mheap.go:904 +0x85 fp=0x7ffd376202b0 sp=0x7ffd37620260 pc=0x42a525
runtime.(*mcentral).grow(0x1120dd8, 0x0)
        /snap/go/7360/src/runtime/mcentral.go:232 +0x79 fp=0x7ffd376202f8 sp=0x7ffd376202b0 pc=0x41b5d9
runtime.(*mcentral).cacheSpan(0x1120dd8, 0x7ffd376203a8)
        /snap/go/7360/src/runtime/mcentral.go:158 +0x2ff fp=0x7ffd37620350 sp=0x7ffd376202f8 pc=0x41b3bf
runtime.(*mcache).refill(0x7f7992305108, 0x2c)
        /snap/go/7360/src/runtime/mcache.go:162 +0xaa fp=0x7ffd37620398 sp=0x7ffd37620350 pc=0x41a8ca
runtime.(*mcache).nextFree(0x7f7992305108, 0x7ffd3762042c, 0x464ea5, 0x7ffd37620438, 0x410f9e)
        /snap/go/7360/src/runtime/malloc.go:882 +0x8d fp=0x7ffd376203d0 sp=0x7ffd37620398 pc=0x40fced
runtime.mallocgc(0x178, 0xaf74a0, 0x7ffd37620401, 0x7ffd376204b8)
        /snap/go/7360/src/runtime/malloc.go:1069 +0x850 fp=0x7ffd37620458 sp=0x7ffd376203d0 pc=0x4106f0
runtime.newobject(0xaf74a0, 0x464e60)
        /snap/go/7360/src/runtime/malloc.go:1177 +0x38 fp=0x7ffd37620488 sp=0x7ffd37620458 pc=0x410958
runtime.malg(0x8000, 0x0)
        /snap/go/7360/src/runtime/proc.go:3944 +0x31 fp=0x7ffd376204c8 sp=0x7ffd37620488 pc=0x4443f1
runtime.mpreinit(0x10f2d20)
        /snap/go/7360/src/runtime/os_linux.go:355 +0x29 fp=0x7ffd376204e8 sp=0x7ffd376204c8 pc=0x435fa9
runtime.mcommoninit(0x10f2d20, 0xffffffffffffffff)
        /snap/go/7360/src/runtime/proc.go:744 +0xf7 fp=0x7ffd37620530 sp=0x7ffd376204e8 pc=0x43d317
runtime.schedinit()
        /snap/go/7360/src/runtime/proc.go:637 +0xaf fp=0x7ffd37620590 sp=0x7ffd37620530 pc=0x43ce8f
runtime.rt0_go(0x7ffd37620698, 0x3, 0x7ffd37620698, 0x0, 0x7f7991b3cbf7, 0x3, 0x7ffd37620698, 0x300008000, 0x46d4a0, 0x0, ...)
        /snap/go/7360/src/runtime/asm_amd64.s:220 +0x125 fp=0x7ffd37620598 sp=0x7ffd37620590 pc=0x46d5e5
Connecting to net:ssb.ter0.net:8008~shs:EISbnu+GMTb50m3G5N8QBCOKtsPbtvJe8dsMC6yYOrw=...
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb0920e, 0x16)
        /snap/go/7360/src/runtime/panic.go:1117 +0x72 fp=0x7fffe037bec0 sp=0x7fffe037be90 pc=0x439452
runtime.sysMap(0xc000000000, 0x4000000, 0x11285d0)
        /snap/go/7360/src/runtime/mem_linux.go:169 +0xc6 fp=0x7fffe037bf00 sp=0x7fffe037bec0 pc=0x41bfe6
runtime.(*mheap).sysAlloc(0x110eaa0, 0x400000, 0x0, 0x0)
        /snap/go/7360/src/runtime/malloc.go:729 +0x1e5 fp=0x7fffe037bfa8 sp=0x7fffe037bf00 pc=0x40f485
runtime.(*mheap).grow(0x110eaa0, 0x1, 0x0)
        /snap/go/7360/src/runtime/mheap.go:1346 +0x85 fp=0x7fffe037c010 sp=0x7fffe037bfa8 pc=0x42b185
runtime.(*mheap).allocSpan(0x110eaa0, 0x1, 0x2c00, 0x0)
        /snap/go/7360/src/runtime/mheap.go:1173 +0x609 fp=0x7fffe037c090 sp=0x7fffe037c010 pc=0x42af89
runtime.(*mheap).alloc.func1()
        /snap/go/7360/src/runtime/mheap.go:910 +0x59 fp=0x7fffe037c0e0 sp=0x7fffe037c090 pc=0x4662d9
runtime.(*mheap).alloc(0x110eaa0, 0x1, 0x220000012c, 0xffffffff)
        /snap/go/7360/src/runtime/mheap.go:904 +0x85 fp=0x7fffe037c130 sp=0x7fffe037c0e0 pc=0x42a525
runtime.(*mcentral).grow(0x1120dd8, 0x0)
        /snap/go/7360/src/runtime/mcentral.go:232 +0x79 fp=0x7fffe037c178 sp=0x7fffe037c130 pc=0x41b5d9
runtime.(*mcentral).cacheSpan(0x1120dd8, 0x7fffe037c228)
        /snap/go/7360/src/runtime/mcentral.go:158 +0x2ff fp=0x7fffe037c1d0 sp=0x7fffe037c178 pc=0x41b3bf
runtime.(*mcache).refill(0x7f69a9a04108, 0x2c)
        /snap/go/7360/src/runtime/mcache.go:162 +0xaa fp=0x7fffe037c218 sp=0x7fffe037c1d0 pc=0x41a8ca
runtime.(*mcache).nextFree(0x7f69a9a04108, 0x7fffe037c22c, 0x464ea5, 0x7fffe037c2b8, 0x410f9e)
        /snap/go/7360/src/runtime/malloc.go:882 +0x8d fp=0x7fffe037c250 sp=0x7fffe037c218 pc=0x40fced
runtime.mallocgc(0x178, 0xaf74a0, 0x7fffe037c301, 0x7fffe037c338)
        /snap/go/7360/src/runtime/malloc.go:1069 +0x850 fp=0x7fffe037c2d8 sp=0x7fffe037c250 pc=0x4106f0
runtime.newobject(0xaf74a0, 0x464e60)
        /snap/go/7360/src/runtime/malloc.go:1177 +0x38 fp=0x7fffe037c308 sp=0x7fffe037c2d8 pc=0x410958
runtime.malg(0x8000, 0x0)
        /snap/go/7360/src/runtime/proc.go:3944 +0x31 fp=0x7fffe037c348 sp=0x7fffe037c308 pc=0x4443f1
runtime.mpreinit(0x10f2d20)
        /snap/go/7360/src/runtime/os_linux.go:355 +0x29 fp=0x7fffe037c368 sp=0x7fffe037c348 pc=0x435fa9
runtime.mcommoninit(0x10f2d20, 0xffffffffffffffff)
        /snap/go/7360/src/runtime/proc.go:744 +0xf7 fp=0x7fffe037c3b0 sp=0x7fffe037c368 pc=0x43d317
runtime.schedinit()
        /snap/go/7360/src/runtime/proc.go:637 +0xaf fp=0x7fffe037c410 sp=0x7fffe037c3b0 pc=0x43ce8f
runtime.rt0_go(0x7fffe037c518, 0x3, 0x7fffe037c518, 0x0, 0x7f69a923bbf7, 0x3, 0x7fffe037c518, 0x300008000, 0x46d4a0, 0x0, ...)
        /snap/go/7360/src/runtime/asm_amd64.s:220 +0x125 fp=0x7fffe037c418 sp=0x7fffe037c410 pc=0x46d5e5
Connecting to net:ssb.the-travel-agency.net:8008~shs:xG7SunE8Z8Zmzc+XTj5pVF0CBZKCx0g1zZu6x5Jl6K4=...
level=error ts=2021-04-25T21:27:25.199966928Z unit=muxrpc remote=/home/justin/.ssb-go/socket event=closed handleErr="muxrpc: serve failed to read from packer: muxrpc: error reading packet pkt-codec: header read failed: read unix @->/home/justin/.ssb-go/socket: read: connection reset by peer" closeErr=null
unit=ssbClient level=warn event="muxrpc.Serve exited" err="muxrpc: serve failed to read from packer: muxrpc: error reading packet pkt-codec: header read failed: read unix @->/home/justin/.ssb-go/socket: read: connection reset by peer"
level=warn event="connect command failed" err="muxrpc: error sending request: muxrpc: session terminated"
level=error run-failure="connect: async call failed.: muxrpc: error sending request: pkt-codec: header write failed: write unix @->/home/justin/.ssb-go/socket: use of closed network connection"
```

**Comment by justinabrahms** [comment] 2021-04-25 21:42
Doh. Just realized the socket error is due to the `go-sbot` crashing too. Here are it's error logs:

```
goroutine 10494886 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc0001a05b4, 0xe17c00, 0x1)
        /snap/go/7360/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0001a05b0)
        /snap/go/7360/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /snap/go/7360/src/sync/mutex.go:81
go.cryptoscope.co/margaret/offset2.(*offsetLog).Append(0xc0001a05b0, 0xe17c60, 0xc08244e480, 0x0, 0x0, 0x0, 0x0)
        /home/justin/go/pkg/mod/go.cryptoscope.co/margaret@v0.1.7-0.20201027171711-332f00d22dd0/offset2/log.go:414 +0x696
go.cryptoscope.co/ssb/message/multimsg.WrappedLog.Append(0xf72f08, 0xc0001a05b0, 0xe8a4a0, 0xde5dc0, 0xc016a740f0, 0xe1a9e0, 0xc016a740f0, 0x1620f20, 0x0)
        /home/justin/src/ssb/message/multimsg/multimsg_wrap.go:64 +0x274
go.cryptoscope.co/ssb/message.MargaretSaver.Save(...)
        /home/justin/src/ssb/message/verifier.go:65
go.cryptoscope.co/ssb/message.(*streamDrain).Verify(0xc0211ef6d0, 0xc0251e8000, 0x1b5, 0xe00, 0x0, 0x0)
        /home/justin/src/ssb/message/drains.go:142 +0x3c6
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).fetchFeed(0xc0000ce000, 0xf6c2b0, 0xc035a46600, 0xc041c46360, 0xf70e18, 0xc0213c36b0, 0xc0199475c321120f, 0x5125fad83b5, 0x1620f20, 0x0, ...)
        /home/justin/src/ssb/plugins/gossip/fetch.go:147 +0x635
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).workFeed.func1(0x0, 0x203020203030303)
        /home/justin/src/ssb/plugins/gossip/fetch.go:61 +0xf7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0347caa50, 0xc0278737c0)
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66

goroutine 10494874 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc0001a05b4, 0xe17c00, 0x1)
        /snap/go/7360/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0001a05b0)
        /snap/go/7360/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /snap/go/7360/src/sync/mutex.go:81
go.cryptoscope.co/margaret/offset2.(*offsetLog).Append(0xc0001a05b0, 0xe17c60, 0xc06f6772c0, 0x0, 0x0, 0x0, 0x0)
        /home/justin/go/pkg/mod/go.cryptoscope.co/margaret@v0.1.7-0.20201027171711-332f00d22dd0/offset2/log.go:414 +0x696
go.cryptoscope.co/ssb/message/multimsg.WrappedLog.Append(0xf72f08, 0xc0001a05b0, 0xe8a4a0, 0xde5dc0, 0xc02f96d360, 0xe1a9e0, 0xc02f96d360, 0x1620f20, 0x0)
        /home/justin/src/ssb/message/multimsg/multimsg_wrap.go:64 +0x274
go.cryptoscope.co/ssb/message.MargaretSaver.Save(...)
        /home/justin/src/ssb/message/verifier.go:65
go.cryptoscope.co/ssb/message.(*streamDrain).Verify(0xc0211ee8c0, 0xc04387a000, 0x1c4, 0x1e00, 0x0, 0x0)
        /home/justin/src/ssb/message/drains.go:142 +0x3c6
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).fetchFeed(0xc0000ce000, 0xf6c2b0, 0xc035a46600, 0xc041c460f0, 0xf70e18, 0xc0213c36b0, 0xc0199475c31317f8, 0x5125f9f89ad, 0x1620f20, 0x0, ...)
        /home/justin/src/ssb/plugins/gossip/fetch.go:147 +0x635
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).workFeed.func1(0x0, 0x403020203020303)
        /home/justin/src/ssb/plugins/gossip/fetch.go:61 +0xf7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0347caa50, 0xc027873280)
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66

goroutine 10599461 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc054a341fc, 0xc0372eb300, 0x1)
        /snap/go/7360/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc054a341f8)
        /snap/go/7360/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /snap/go/7360/src/sync/mutex.go:81
go.cryptoscope.co/ssb/message.(*streamDrain).Seq(0xc054a341e0, 0x0)
        /home/justin/src/ssb/message/drains.go:117 +0x9d
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).fetchFeed(0xc0000ce000, 0xf6c2b0, 0xc08f31a240, 0xc02c3c3920, 0xf70e18, 0xc09057be40, 0xc0199558f552cac0, 0x5e5fae3b437, 0x1620f20, 0x0, ...)
        /home/justin/src/ssb/plugins/gossip/fetch.go:97 +0x19c
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).workFeed.func1(0x0, 0x0)
        /home/justin/src/ssb/plugins/gossip/fetch.go:61 +0xf7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc045ccfc20, 0xc03f7cbc40)
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66

goroutine 10599360 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc03901c24c, 0xc037221100, 0x1)
        /snap/go/7360/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc03901c248)
        /snap/go/7360/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /snap/go/7360/src/sync/mutex.go:81
go.cryptoscope.co/ssb/message.(*streamDrain).Seq(0xc03901c230, 0x0)
        /home/justin/src/ssb/message/drains.go:117 +0x9d
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).fetchFeed(0xc0000ce000, 0xf6c2b0, 0xc08f31a240, 0xc01566a750, 0xf70e18, 0xc09057be40, 0xc01995590aa058a7, 0x5e60bcc0caa, 0x1620f20, 0x0, ...)
        /home/justin/src/ssb/plugins/gossip/fetch.go:97 +0x19c
go.cryptoscope.co/ssb/plugins/gossip.(*LegacyGossip).workFeed.func1(0x1, 0xe8a008)
        /home/justin/src/ssb/plugins/gossip/fetch.go:61 +0xf7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc045ccfc20, 0xc03f7356c0)
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/justin/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by cryptix** [comment] 2021-04-30 09:27
Hey @justinabrahms, sorry you ran into this. May I ask what kind of device you are using this on?

This feels vaguely similar to #86.

**Comment by justinabrahms** [comment] 2021-08-09 06:25
I don't really recall. :-/   The only things I have which have so little ram are a little raspberri pi, so you're probably right about it being a duplicate.

**Comment by decentral1se** [comment] 2022-10-27 23:53
Potentially also a dupe of #124? :thinking: 

https://github.com/ssbc/go-ssb/issues/86#issuecomment-1294242469

**Comment by decentral1se** [comment] 2022-11-07 17:38
https://github.com/ssbc/go-ssb/issues/95#issuecomment-1294243044

**Closed by decentral1se** 2022-11-07 17:38 UTC
Labels: bug, question
