### ISSUE TITLE
If running go-sbot on alternate port, sbotcli doesn't find it

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#214] opened 2022-11-20 15:58 UTC
For my configuration, I am running go-sbot on port 8009.  When I run that that way, everything seems to work fine.  But then if I run `sbotcli call whoami` I get the following error:

```
level=error run-failure="init: failed to connect to 127.0.0.1:8008|@[ID redacted].ed25519: error dialing: error wrapping connection: secrethandshake: failed during data transfer of receiving server auth: EOF"
```

So even though this is specified in `config.toml`:

```
# Address to listen on
lis = ":8009"
```

sbotcli does not seem to be using that.

**Comment by mycognosist** [comment] 2022-11-20 16:03
@KyleMaas 

You should be able to define a non-standard port using the `--addr` flag for `sbotcli`.

For example:

`sbotcli --addr "localhost:8009" call whoami`

**Comment by KyleMaas** [comment] 2022-11-20 16:25
Sure, and if I do that, it does try to connect on the wrong port (doesn't work yet, but that's a different issue).

The problem is that of expectations.  Typically, I would expect that two binaries in the same package, which share the same documentation, would also use the same configuration file.  It looks like it should be common between the two of them.  If it's not, how would I configure the defaults for sbotcli so I don't have the specify the port on every cli call?

**Comment by mycognosist** [comment] 2022-11-20 16:33
I'll defer to @decentral1se on this one.

Using the latest builds of both binaries, I experience the behaviour you're expecting, ie. I'm running `go-sbot` on a non-standard port (`8021`, defined in `~/.ssb-go/config.toml`) and my `sbotcli` commands work without needing to pass any flags.

**Comment by KyleMaas** [comment] 2022-11-20 22:06
Strange it would work for you, because while I can't say I'm terribly familiar with Go yet, I'm not really seeing anything in here that pulls configuration from anywhere other than the command line:

https://github.com/ssbc/go-ssb/blob/8a69bc6cb5ddd619f5ad5d90f61f5f49a2da7957/cmd/sbotcli/main.go#L73

Here's what I would be expecting from go-sbot:

https://github.com/ssbc/go-ssb/blob/0c73e866b8aa1b156efd42105a9596f66cdb587a/cmd/go-sbot/main.go#L133

**Comment by decentral1se** [comment] 2022-11-21 09:25
Yeh, you need to pass `--addr` on all calls atm. This is a duplicate of https://github.com/ssbc/go-ssb/issues/151 then, let's continue the discussion there? I had a proposal to adjust the config which may be a breaking change, so some input is needed. Thanks for the report!

**Closed by decentral1se** 2022-11-21 09:25 UTC
